Repository amplitude/amplitude-docs, pull requests merged in 2025-08, with the labels that each got.

#903 DOC-815 update build script
  build.sh
Labels: Doesn't need review

#901 DOC-764 Torchlight -> Prism
  .vscode/doc-snippets.code-snippets
  app/Markdown/Copy/TorchlightWithCopyExtension.php
  app/Providers/AppServiceProvider.php
  build.sh
  composer.json
  composer.lock
  content/collections/android_sdk/en/migrate-to-the-android-kotlin-sdk.md
  content/collections/api/en/batch-event-upload.md
  content/collections/api/en/taxonomy.md
  content/collections/browser_sdk/en/autocapture-plugin.md
  content/collections/browser_sdk/en/browser-sdk-2.md
  content/collections/browser_sdk/en/migrate-from-browser-sdk-1-0-to-2-0.md
  content/collections/browser_sdk/en/migrate-from-marketing-analytics-to-browser-sdk-2-0.md
  content/collections/experiment-apis/en/experiment-management-api-flags.md
  content/collections/experiment-apis/en/experiment-management-api-version-endpoints.md
  content/collections/experiment-sdks/en/experiment-android.md
  content/collections/experiment-sdks/en/experiment-ios.md
  content/collections/experiment-sdks/en/experiment-react-native.md
  content/collections/flutter_sdk/en/flutter-sdk-4-0-migration-guide.md
  content/collections/get-started/en/autocapture.md
  content/collections/guides_and_surveys/en/guides-and-surveys-android-sdk.md
  content/collections/guides_and_surveys/en/guides-and-surveys-ios-sdk.md
  content/collections/guides_and_surveys/en/guides-and-surveys-rn-sdk.md
  content/collections/instrumentation/en/sdk-quickstart.md
  content/collections/ios_sdk/en/ios-sdk-migration-guide.md
  content/collections/node_js_sdk/en/node-js-sdk-migration-guide.md
  content/collections/node_js_sdk/en/node-js-sdk.md
  content/collections/pages/en/components.md
  content/collections/react_native_sdk/en/migrate-to-the-latest-react-native-sdk.md
  content/collections/session-replay/en/session-replay-android-plugin.md
  content/collections/session-replay/en/session-replay-integration-with-segment.md
  content/collections/session-replay/en/session-replay-plugin.md
  content/collections/session-replay/en/session-replay-standalone-sdk.md
  content/collections/source-catalog/en/amazon-s3.md
  content/collections/web_experiment/en/implementation.md
  package-lock.json
  package.json
  public/docs/css/site.css
  public/docs/fonts/js/api-table.js
  public/docs/fonts/js/interactive-exposure-tracking-table.js
  public/docs/fonts/js/site.js
  public/docs/js/site.js.LICENSE.txt
  public/mix-manifest.json
  resources/docs/css/dracula-prism.css
  resources/docs/css/prism.css
  resources/docs/js/site.js
  resources/views/_tab.antlers.html
  resources/views/default.antlers.html
  resources/views/layout.antlers.html
  resources/views/partials/_admonition.antlers.html
  resources/views/partials/code/_snippet.antlers.html
  resources/views/partials/session-replay/_sr-web-mismatch.antlers.html
  webpack.mix.js
Labels: Doesn't need review

#918 Update experiment-quick-start.md
  content/collections/experiment/en/experiment-quick-start.md
Labels: Doesn't need review

#921 Update destinations.md
  content/collections/cdp/en/destinations.md
Labels: Needs review

#926 Update to include group cohort to remote evaluation
  content/collections/experiment/en/cohort-targeting.md
  content/collections/experiment/en/local-evaluation.md
Labels: Doesn't need review

#927 Doc 834
  content/collections/faq_and_troubleshooting/en/the-datepicker.md
Labels: Doesn't need review

#928 Update the-datepicker.md
  content/collections/faq_and_troubleshooting/en/the-datepicker.md
Labels: Doesn't need review

#931 DOC-843 better bundle size fallback
  app/Console/Commands/DebugBundleCache.php
  app/Tags/BundlePhobia.php
  build.sh
  config/app.php
  public/docs/css/site.css
  resources/views/partials/_bundle-size.antlers.html
  routes/api.php
Labels: Doesn't need review

#961 document networkTracking request and response headers/body
  content/collections/browser_sdk/en/browser-sdk-2.md
Labels: draft_do_not_merge
